sudo: false
language: node_js
node_js:
  - 18
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false

before_script:
  - nvm install node
  - npm i
script:
  - npm run validate
